#!/usr/bin/env python3
import secrets
import sys
import time

import jwt


def generate_keys():
    """Generates Supabase JWT Secret, Anon Key, and Service Role Key."""

    # 1. Generate a strong JWT Secret
    jwt_secret = secrets.token_urlsafe(40)  # ~53 characters, strong enough

    current_time = int(time.time())
    expiry_time = current_time + (10 * 365 * 24 * 60 * 60)  # 10 years from now

    # 2. Generate Anon Key
    anon_payload = {"role": "anon", "iss": "supabase", "iat": current_time, "exp": expiry_time}
    anon_key = jwt.encode(anon_payload, jwt_secret, algorithm="HS256")

    # 3. Generate Service Role Key
    service_role_payload = {
        "role": "service_role",
        "iss": "supabase",
        "iat": current_time,
        "exp": expiry_time,
    }
    service_role_key = jwt.encode(service_role_payload, jwt_secret, algorithm="HS256")

    # Output in .env format
    print("# Generated by scripts/generate_supabase_keys.py")
    print(f"JWT_SECRET={jwt_secret}")
    print(f"ANON_KEY={anon_key}")
    print(f"SERVICE_ROLE_KEY={service_role_key}")


if __name__ == "__main__":
    try:
        import jwt
    except ImportError:
        print(
            "Error: 'pyjwt' is required. Run 'uv pip install pyjwt' or 'pip install pyjwt'",
            file=sys.stderr,
        )
        sys.exit(1)

    generate_keys()
